import React from 'react';
import WaveformVisualizer from './WaveformVisualizer';

export const buildAiAnalysisRenderProps = (p: any) => ({
  currentStep: p.currentStep,
  allResumes: p.allResumes as any[],
  searchQuery: p.searchQuery,
  setSearchQuery: p.setSearchQuery,
  isOptimizedOpen: p.isOptimizedOpen,
  setIsOptimizedOpen: p.setIsOptimizedOpen,
  isUnoptimizedOpen: p.isUnoptimizedOpen,
  setIsUnoptimizedOpen: p.setIsUnoptimizedOpen,
  handleResumeSelectBack: p.handleResumeSelectBack,
  handleResumeSelect: (
    resumeId: string | number,
    preferReport: boolean,
    targetStep?: 'chat' | 'comparison' | 'final_report'
  ) => {
    void p.handleResumeSelect(resumeId, preferReport, targetStep);
  },
  selectedResumeId: p.selectedResumeId,
  resumeReadState: p.resumeReadState,
  isInterviewMode: p.isInterviewMode,
  pointsRemaining: p.pointsRemaining,
  isSameResumeId: p.isSameResumeId,
  resumeData: p.resumeData,
  targetCompany: p.targetCompany,
  setTargetCompany: p.setTargetCompany,
  jdText: p.jdText,
  setJdText: p.setJdText,
  analysisMode: p.analysisMode,
  setAnalysisMode: p.setAnalysisMode,
  isUploading: p.isUploading,
  handleScreenshotUpload: p.handleScreenshotUpload,
  handleStepBack: p.handleStepBack,
  handleFinalReportBack: p.handleFinalReportBack,
  handleBackToJdInputFromFinalReport: p.handleBackToJdInputFromFinalReport,
  navigateToStep: p.navigateToStep,
  setCurrentStep: p.setCurrentStep,
  handleStartAnalysisClick: p.handleStartAnalysisClick,
  startAnalysis: p.startAnalysis,
  onRestartCompletedInterviewScene: p.onRestartCompletedInterviewScene,
  interviewEntryConfirmPendingRef: p.interviewEntryConfirmPendingRef,
  score: p.score,
  originalScore: p.originalScore,
  getScoreColor: p.getScoreColor,
  onFinalReportFeedback: p.onFinalReportFeedback,
  onInterviewReportFeedback: p.onInterviewReportFeedback,
  ToastOverlay: p.ToastOverlay,
  WaveformVisualizer: (props: any) => <WaveformVisualizer {...props} visualizerData={p.visualizerData} />,
  interruptCurrentThinking: p.interruptCurrentThinking,
  endInterviewFromChat: p.endInterviewFromChat,
  skipInterviewQuestionFromChat: p.skipInterviewQuestionFromChat,
  handleRestartInterview: p.handleRestartInterview,
  userAvatar: p.userAvatar,
  chatMessages: p.chatMessages,
  isSending: p.isSending,
  hasPendingReply: p.hasPendingReply,
  messagesEndRef: p.messagesEndRef,
  messagesContainerRef: p.messagesContainerRef,
  handleMessagesScroll: p.handleMessagesScroll,
  expandedReferences: p.expandedReferences,
  setExpandedReferences: p.setExpandedReferences,
  parseReferenceReply: p.parseReferenceReply,
  audioPlayerRef: p.audioPlayerRef,
  playingAudioId: p.playingAudioId,
  setPlayingAudioId: p.setPlayingAudioId,
  hasVoiceBlobForMsg: p.hasVoiceBlobForMsg,
  transcribingByMsgId: p.transcribingByMsgId,
  transcribeExistingVoiceMessage: p.transcribeExistingVoiceMessage,
  keyboardOffset: p.keyboardOffset,
  inputBarHeight: p.inputBarHeight,
  inputBarRef: p.inputBarRef,
  isKeyboardOpen: p.isKeyboardOpen,
  audioError: p.audioError,
  setAudioError: p.setAudioError,
  inputMode: p.inputMode,
  isRecording: p.isRecording,
  audioSupported: p.audioSupported,
  holdCancel: p.holdCancel,
  toggleChatInputMode: p.toggleChatInputMode,
  textareaRef: p.textareaRef,
  inputMessage: p.inputMessage,
  setInputMessage: p.setInputMessage,
  handleSendMessage: () => {
    void p.handleSendMessage();
  },
  holdTalkBtnRef: p.holdTalkBtnRef,
  onHoldPointerDown: p.onHoldPointerDown,
  onHoldPointerMove: p.onHoldPointerMove,
  onHoldPointerUp: p.onHoldPointerUp,
  onHoldPointerCancel: p.onHoldPointerCancel,
  interviewPlan: p.interviewPlan,
  interviewAnsweredCount: p.interviewAnsweredCount,
  currentQuestionElapsedSec: p.currentQuestionElapsedSec,
  getInterviewerTitle: p.getInterviewerTitle,
  getInterviewerAvatarUrl: p.getInterviewerAvatarUrl,
  onChatMessageFeedback: p.onChatMessageFeedback,
  postInterviewSummary: p.effectivePostInterviewSummary,
  interviewReportSummary: p.interviewReportSummary,
  interviewReportScore: p.interviewReportScore,
  interviewReportAdvice: p.interviewReportAdvice,
  postInterviewOriginalResume: p.postInterviewOriginalResume,
  postInterviewGeneratedResume: p.postInterviewGeneratedResume,
  postInterviewAnnotations: p.postInterviewAnnotations,
  handlePostInterviewFeedback: p.handlePostInterviewFeedback,
  handleCompleteAndSavePostInterview: p.handleCompleteAndSavePostInterview,
  finalReportSummary: p.finalReportOverride?.summary || p.finalReportSummary || '诊断完成，请查看结果。',
  finalReportAdvice: p.finalReportOverride?.advice || p.finalReportAdvice || [],
  finalReportScore: p.finalReportOverride?.score ?? p.finalReportScore ?? 0,
  handleStartInterviewFromFinalReport: p.handleStartInterviewFromFinalReport,
  handleViewResumeFromFinalReport: p.handleViewResumeFromFinalReport,
  isFinalReportGenerating: p.isFinalReportGenerating,
});
