import React from 'react';
import WaveformVisualizer from './WaveformVisualizer';

export const buildAiAnalysisRenderProps = (p: any) => ({
  currentStep: p.currentStep,
  allResumes: p.allResumes as any[],
  searchQuery: p.searchQuery,
  setSearchQuery: p.setSearchQuery,
  isOptimizedOpen: p.isOptimizedOpen,
  setIsOptimizedOpen: p.setIsOptimizedOpen,
  isUnoptimizedOpen: p.isUnoptimizedOpen,
  setIsUnoptimizedOpen: p.setIsUnoptimizedOpen,
  handleResumeSelectBack: p.handleResumeSelectBack,
  handleResumeSelect: (resumeId: string | number, preferReport: boolean) => {
    void p.handleResumeSelect(resumeId, preferReport);
  },
  selectedResumeId: p.selectedResumeId,
  resumeReadState: p.resumeReadState,
  isInterviewMode: p.isInterviewMode,
  pointsRemaining: p.pointsRemaining,
  isSameResumeId: p.isSameResumeId,
  resumeData: p.resumeData,
  targetCompany: p.targetCompany,
  setTargetCompany: p.setTargetCompany,
  jdText: p.jdText,
  setJdText: p.setJdText,
  isUploading: p.isUploading,
  handleScreenshotUpload: p.handleScreenshotUpload,
  handleStepBack: p.handleStepBack,
  setCurrentStep: p.setCurrentStep,
  handleStartAnalysisClick: p.handleStartAnalysisClick,
  showJdEmptyModal: p.showJdEmptyModal,
  setShowJdEmptyModal: p.setShowJdEmptyModal,
  startAnalysis: p.startAnalysis,
  hasJdInput: p.hasJdInput,
  score: p.score,
  originalScore: p.originalScore,
  report: p.report,
  getScoreColor: p.getScoreColor,
  handleAnalyzeOtherResume: () => {
    void p.startAnalysis(undefined, { preserveReportOnError: true, bypassCache: true });
  },
  handleStartMicroInterview: p.handleStartMicroInterview,
  handleRetryAnalysisFromIntro: p.handleRetryAnalysisFromIntro,
  ToastOverlay: p.ToastOverlay,
  WaveformVisualizer: (props: any) => <WaveformVisualizer {...props} visualizerData={p.visualizerData} />,
  endInterviewFromChat: p.endInterviewFromChat,
  handleRestartInterview: p.handleRestartInterview,
  userAvatar: p.userAvatar,
  chatMessages: p.chatMessages,
  isSending: p.isSending,
  messagesEndRef: p.messagesEndRef,
  messagesContainerRef: p.messagesContainerRef,
  handleMessagesScroll: p.handleMessagesScroll,
  expandedReferences: p.expandedReferences,
  setExpandedReferences: p.setExpandedReferences,
  parseReferenceReply: p.parseReferenceReply,
  audioPlayerRef: p.audioPlayerRef,
  playingAudioId: p.playingAudioId,
  setPlayingAudioId: p.setPlayingAudioId,
  hasVoiceBlobForMsg: p.hasVoiceBlobForMsg,
  transcribingByMsgId: p.transcribingByMsgId,
  transcribeExistingVoiceMessage: p.transcribeExistingVoiceMessage,
  keyboardOffset: p.keyboardOffset,
  inputBarHeight: p.inputBarHeight,
  inputBarRef: p.inputBarRef,
  isKeyboardOpen: p.isKeyboardOpen,
  audioError: p.audioError,
  setAudioError: p.setAudioError,
  inputMode: p.inputMode,
  isRecording: p.isRecording,
  audioSupported: p.audioSupported,
  holdCancel: p.holdCancel,
  toggleChatInputMode: p.toggleChatInputMode,
  textareaRef: p.textareaRef,
  inputMessage: p.inputMessage,
  setInputMessage: p.setInputMessage,
  handleSendMessage: () => {
    void p.handleSendMessage();
  },
  holdTalkBtnRef: p.holdTalkBtnRef,
  onHoldPointerDown: p.onHoldPointerDown,
  onHoldPointerMove: p.onHoldPointerMove,
  onHoldPointerUp: p.onHoldPointerUp,
  onHoldPointerCancel: p.onHoldPointerCancel,
  interviewPlan: p.interviewPlan,
  interviewAnsweredCount: p.interviewAnsweredCount,
  getInterviewerTitle: p.getInterviewerTitle,
  getInterviewerAvatarUrl: p.getInterviewerAvatarUrl,
  postInterviewSummary: p.effectivePostInterviewSummary,
  postInterviewOriginalResume: p.postInterviewOriginalResume,
  postInterviewGeneratedResume: p.postInterviewGeneratedResume,
  postInterviewAnnotations: p.postInterviewAnnotations,
  handlePostInterviewFeedback: p.handlePostInterviewFeedback,
  handleCompleteAndSavePostInterview: p.handleCompleteAndSavePostInterview,
  finalReportSummary: p.finalReportOverride?.summary || p.finalReportSummary,
  finalReportAdvice: p.finalReportOverride?.advice || p.finalReportAdvice,
  finalReportScore: p.finalReportOverride?.score ?? p.finalReportScore,
  handleStartInterviewFromFinalReport: p.handleStartInterviewFromFinalReport,
});

